[graph]
all-features = true
no-default-features = false

[advisories]
version = 2
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []
informational_warnings = ["notice", "unmaintained"]

[licenses]
version = 2
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "Zlib",
    "CC0-1.0",
]
exceptions = []

[bans]
version = 2
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
deny = []
skip = []
skip-tree = []

[sources]
version = 2
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

